apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: qa-app
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qa-app
  template:
    metadata:
      labels:
        app: qa-app
    spec:
      containers:
      - name: qa-app
<<<<<<< HEAD
        image: hendrikfs/qa-app:v2
=======
        image: hendrikfs/qa-app:latest
>>>>>>> 871416ddb463307567f655c29bfa318bf3568fc9
        ports:
        - containerPort: 80

  strategy:
    blueGreen:
      activeService: qa-app-service
      previewService: qa-app-preview
      autoPromotionEnabled: true
