apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
  namespace: dev
spec:
  selector:
    app: dev-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
