apiVersion: v1
kind: Service
metadata:
  name: qa-app-service
  namespace: qa
spec:
  selector:
    app: qa-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
