apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dev-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-app
        image: hendrikfs/dev-app:v3-5958c13
        ports:
        - containerPort: 80

  strategy:
    blueGreen:
      activeService: dev-app-service
      previewService: dev-app-preview
      autoPromotionEnabled: true