apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: prod-app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: hendrikfs/prod-app:v3-b8aad34
        ports:
        - containerPort: 80

  strategy:
    blueGreen:
      activeService: prod-app-service
      previewService: prod-app-preview
      autoPromotionEnabled: true
