apiVersion: v1
kind: Service
metadata:
  name: prod-app-service
  namespace: prod
spec:
  selector:
    app: prod-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
